language: objective-c
osx_image: xcode13.4

branches:
  only:
  - master

env:
  global:
  - NODE_VERSION=stable

install:
  - brew tap wix/brew
  - brew install applesimutils
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION

  - cd AwesomeProject && npm install react-native-cli --global & cd ..
  - cd AwesomeProject && npm install detox-cli --global && cd ..

script:
  - cd AwesomeProject
  - detox build --configuration ios.sim.release
  - detox test --configuration ios.sim.release --cleanup
